from . import cesar
from . import matching
from . import reverse_animals
from . import reverse_text
from . import suite_croissante
from . import test_cesar
from . import test_matching
from . import test_reverse_animals
from . import test_reverse_text
from . import test_suite_croissante
